---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 'latest'

inputs:
  - name: project-src

outputs:
  - name: build-output

run:
  path: sh
  args:
  - -exc
  - |
    whoami
    env
    ls -la
    sh project-src/ci/build.sh