---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk-alpine'

inputs:
  - name: project-src

outputs:
  - name: build-output

run:
  path: sh
  args:
  - -exc
  - |
    whoami
    env
    ls -la
    cd project-src
    ls -la
    cd ci
    ls -la
    chmod 755 build.sh
    ./build.sh
  